version: "3.3"

services:
  redis:
    image: redis:5.0
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root/app:Z
    environment:
      API_CONTACTS_LIMIT: 3
      CACHE_TTL_SECONDS: 20
      LOGLEVEL: trace
      REDIS_URL: redis://redis
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped
