version: "3.3"

services:
  redis:
    image: redis:5.0
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root/app:Z
    environment:
      REDIS_URL: redis://redis
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped
